Local path installation support
motaparthipavankumar/keycloak pull request #3
Opened 2022-01-11 07:24 UTC by motaparthipavankumar

Local path installation support:

- Changes to pass local keycloak zip file.
-  Changes to pass local RHSSO zip file.

2022-01-14 03:35 UTC, sabre1041 requested changes
While reviewing the collection, I found myself taking a step back and determining the matrix of possibilities: These include distribution types and download methods:

1. First determine what distribution type you want to install (upstream keycloak/RHSSO)
2. How are you going obtain the source (RHN/remote location/local on control node)

These factors drive the logic of the collection

2022-01-14 03:35 UTC, sabre1041 commented on README.md
> +### Choosing between Red Hat products and upstream(Keycloak) project
```suggestion
### Choosing between Red Hat products and upstream (Keycloak) project
```

2022-01-14 03:35 UTC, sabre1041 commented on README.md
> +The roles supports installing Keycloak or Red Hat Single Sign-On in following ways
```suggestion
The roles supports installing Keycloak or Red Hat Single Sign-On in the following ways
```

2022-01-14 03:35 UTC, sabre1041 commented on README.md
> +keycloak_zip_file_local_path: <local path of keycloak zip file>
Need to denote that this is local on the Ansible control node

2022-01-14 03:35 UTC, sabre1041 commented on README.md
> +#### Install RHSSO from the Customer Portal, when the following variables are defined
```suggestion
#### Install RHSSO from the Red Hat Customer Portal, when the following variables are defined
```

2022-01-14 03:35 UTC, sabre1041 commented on roles/keycloak/README.md
> +|`keycloak_zip_file_local_path` | Full local path of Keycloak zip file  | `/tmp/keycloak/keycloak-16.1.0.zip` |
Why do we have separate paths for RHSSO/keycloak. Why not just have a path for local file?

2022-01-14 03:35 UTC, sabre1041 commented on roles/keycloak/defaults/main.yml
> +keycloak_rhsso_enable: "{{ True if rhsso_rhn_id is defined or rhsso_zip_file_local_path is defined  or rhsso_source_download_url is defined else False }}"
Why cant this be used as the determination of whether this is upstream or keycloak?

2022-01-14 15:49 UTC, motaparthipavankumar commented on roles/keycloak/defaults/main.yml
> +keycloak_rhsso_enable: "{{ True if rhsso_rhn_id is defined or rhsso_zip_file_local_path is defined  or rhsso_source_download_url is defined else False }}"
Actually that's how we are determining if it is upstream or RHSSO

2022-01-18 17:22 UTC, motaparthipavankumar commented
Addressed all comments

2022-01-18 17:22 UTC, merged